'use client';
import MeetingPanel from './meeting-panel';
import QueuePanel from './queue-panel';
import GroqSettings from './settings/groq-settings';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Mic,FileText,Download,Upload,Save,Headphones} from 'lucide-react';
const labels:Record<string,string>={raw:'原始逐字稿',reviewed:'校正逐字稿',corrections:'校正紀錄',summary:'會議摘要'};
async function api(path:string,options?:RequestInit){const r=await fetch('/api/audio/'+path,options);const d:any=await r.json();if(!r.ok)throw new Error(d.error||'請求失敗');return d;}
const json=(b:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
export default function Home(){
 const [jobs,setJobs]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[kind,setKind]=useState('raw'),[text,setText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[health,setHealth]=useState<any>(null),[prompt,setPrompt]=useState('');
 async function refresh(){const rows=await api('jobs');setJobs(rows);setHealth(await api('health'));const id=new URLSearchParams(window.location.search).get('meeting');if(id){const r=rows.find((x:any)=>x.id===id)||await api('jobs/'+encodeURIComponent(id));await select(r,'summary');}}
 useEffect(()=>{const reload=()=>{refresh().catch(e=>setMessage(e.message));};reload();window.addEventListener('groq-settings-updated',reload);return()=>window.removeEventListener('groq-settings-updated',reload);},[]);
 async function select(r:any,k=kind){if(busy)return;setBusy(true);try{const doc=await api(`jobs/${r.id}/documents/${k}`);setSelected(r);window.history.replaceState(null,'','?meeting='+encodeURIComponent(r.id));setKind(k);setText(doc.text);setMessage('');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);try{const job=await api('jobs',json({name:file.name,size:file.size}));for(let n=0;n<job.parts;n++){setMessage(`上傳 ${file.name} · ${Math.round(n/job.parts*100)}%`);await api(`jobs/${job.id}/parts/${n}`,{method:'PUT',body:file.slice(n*job.partSize,(n+1)*job.partSize)});}await api(`jobs/${job.id}/complete`,json({}));await refresh();setSelected({...job,name:file.name,size:file.size,state:'stored'});setKind('raw');setText('');setMessage('音檔已保存');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function save(){setBusy(true);try{await api(`jobs/${selected.id}/documents/${kind}`,json({text}));setMessage('已保存新版本，先前版本保留');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function run(){setBusy(true);setMessage('正在辨識，請保留此頁面');try{await api(`jobs/${selected.id}/transcribe`,json({prompt}));const doc=await api(`jobs/${selected.id}/documents/raw`);setKind('raw');setText(doc.text);await refresh();setMessage('轉錄完成，請檢查專業名詞與數字');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 function download(){const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`${selected.name}.${kind}.md`;a.click();URL.revokeObjectURL(u);}
 return <main className="min-h-screen"><header className="bg-[#142b50] text-white px-6 py-5 flex items-center gap-3"><Mic aria-hidden className="text-[#70b8ff]"/><h1 className="text-xl font-semibold">會議語音筆記</h1><span className="ml-auto text-sm text-blue-100">私人工作空間</span></header>
 <div className="max-w-[1440px] mx-auto grid lg:grid-cols-[320px_1fr] gap-6 p-5 md:p-8"><aside className="space-y-5"><section className="bg-white border rounded-xl p-5"><h2 className="font-semibold text-lg mb-4">新增錄音</h2><label className="block border-2 border-dashed border-blue-200 rounded-lg p-5 text-center cursor-pointer"><Upload className="mx-auto mb-3 text-blue-700" aria-hidden/><span className="block mb-2">選擇音檔</span><Input aria-label="上傳音檔" type="file" accept="audio/*" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value='';}}/><span className="block text-sm text-slate-500 mt-3">保留原始錄音，逐字稿另存版本</span></label></section>
 <section><h2 className="font-semibold mb-3">我的錄音 <span className="text-slate-500 font-normal">{jobs.length}</span></h2><div className="space-y-2">{jobs.map(r=><button key={r.id} disabled={busy} onClick={()=>select(r)} className={`w-full text-left rounded-lg border p-4 ${selected?.id===r.id?'bg-blue-50 border-blue-500':'bg-white'}`}><span className="block break-all font-medium">{r.name}</span><span className="block text-sm text-slate-500 mt-2">{r.parts===0?'分段工作':r.state==='uploading'?'上傳未完成':r.state==='transcribed'?'已轉錄':r.state==='processing'?'轉錄中':'已保存'} · {(r.size/1048576).toFixed(1)} MB</span></button>)}{jobs.length===0&&<p className="text-slate-500 text-sm">目前沒有錄音。</p>}</div></section></aside>
 <section className="min-w-0"><GroqSettings/><div className="mb-5 p-4 rounded-lg border bg-white"><strong className="text-sm">{health?.ai?'語音辨識已連線':'語音辨識尚未連線'}</strong><p className="text-sm text-slate-600 mt-1">{health?.ai?'長錄音交給專屬 Work 對話先切片再上傳，分段工作會保存進度並依額度排隊。':'音檔保存與逐字稿編輯可先使用；轉錄需要接通語音模型。'}</p></div>
 {message&&<p role="status" className="mb-4 p-3 border border-blue-200 bg-blue-50 rounded-lg break-words">{message}</p>}
 {selected?<div className="bg-white border rounded-xl overflow-hidden"><div className="p-5 border-b flex flex-wrap items-center gap-3"><Headphones className="text-blue-700" aria-hidden/><h2 className="font-semibold flex-1 break-all">{selected.name}</h2>{selected.parts!==0&&<a className="text-sm text-blue-700 underline" href={`/api/audio/jobs/${selected.id}/original`}>下載原始音檔</a>}</div>{selected.parts===0?<QueuePanel id={selected.id} onDone={()=>select(selected,'raw')}/>:<div className="p-5 border-b space-y-3"><label htmlFor="terms" className="text-sm">專業名詞與會議背景</label><Input id="terms" placeholder="例如：會議主題、產品名稱、專業縮寫" value={prompt} onChange={e=>setPrompt(e.target.value)}/><Button disabled={busy||!health?.ai||selected.size>8*1048576} onClick={run}><Mic/>開始轉錄</Button>{selected.size>8*1048576&&<p className="text-sm text-slate-500">長錄音已保存。請交給專屬 Work 對話先解碼切片，再建立分段轉錄工作。</p>}</div>}
 <MeetingPanel id={selected.id} revision={message}/><div className="flex flex-wrap gap-2 p-4 border-b">{Object.entries(labels).map(([k,v])=><Button key={k} variant={kind===k?'default':'outline'} disabled={busy} onClick={()=>select(selected,k)}>{v}</Button>)}</div>
 <div className="p-5"><label htmlFor="document" className="block mb-3 font-medium">{labels[kind]}</label><Textarea id="document" className="min-h-[400px] text-base resize-y" disabled={busy} value={text} onChange={e=>setText(e.target.value)} placeholder="轉錄完成後會顯示原始文字，也可以貼上既有逐字稿。校正與摘要請分別保存。"/><div className="mt-4 flex flex-wrap gap-3"><Button onClick={save} disabled={busy}><Save/>保存版本</Button><Button onClick={download} disabled={!text} variant="outline"><Download/>下載 Markdown</Button></div><p className="text-sm text-slate-500 mt-4">人名、金額與聽不清楚的段落請標記待確認，保留原始逐字稿。</p></div></div>:<div className="bg-white border rounded-xl min-h-[500px] flex flex-col items-center justify-center p-8 text-center"><FileText size={44} className="text-blue-600 mb-5" aria-hidden/><h2 className="text-2xl font-semibold mb-3">從錄音開始，留下清楚的會議紀錄</h2><p className="text-slate-500 max-w-md">選擇一份錄音，查看原始逐字稿、校正內容與會議摘要。</p></div>}
 </section></div></main>;
}
