'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
export default function GroqSettings(){
 const [key,setKey]=useState(''),[status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function request(options?:RequestInit){const r=await fetch('/api/audio/settings/groq',{cache:'no-store',...options});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'設定失敗');return data;}
 useEffect(()=>{request().then(setStatus).catch(e=>setMessage(e.message));},[]);
 async function update(remove=false){setBusy(true);setMessage('');try{const data=await request(remove?{method:'DELETE'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});setStatus(data);setKey('');setMessage(remove?'已刪除 Key。':'已驗證並儲存，可以開始轉錄。');window.dispatchEvent(new Event('groq-settings-updated'));}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <section id="groq-settings" className="bg-white border rounded-xl p-5 mb-5 scroll-mt-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-semibold">語音辨識設定</h2><span className="text-sm text-slate-600">{status?(status.configured?'Groq Key 已設定':'尚未設定 Groq Key'):'讀取設定中'}</span></div><p className="text-sm text-slate-600 mt-2 mb-4">貼入你的 Groq API Key，驗證後加密保存。開始轉錄時，音檔會送至 Groq 處理。</p><form autoComplete="off" onSubmit={e=>{e.preventDefault();update();}}><label htmlFor="groq-key" className="block text-sm font-medium mb-2">Groq API Key</label><Input id="groq-key" name="groq-api-key" type="password" autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={300} value={key} onChange={e=>setKey(e.target.value)} placeholder={status?.configured?'貼入新 Key 以更換':'貼上 gsk_ 開頭的 Key'} disabled={busy}/><div className="flex flex-wrap items-center gap-3 mt-3"><Button type="submit" disabled={busy||!key.trim()||!status?.storageReady}>{busy?'處理中…':'驗證並儲存'}</Button>{status?.configured&&<Button type="button" variant="outline" disabled={busy} onClick={()=>update(true)}>刪除 Key</Button>}<a className="text-sm text-blue-700 underline" href="https://console.groq.com/keys" target="_blank" rel="noreferrer">取得 Groq Key</a></div></form>{message&&<p role="status" className="mt-3 text-sm break-words">{message}</p>}{status&&!status.storageReady&&<p role="alert" className="mt-3 text-sm">加密儲存服務尚未就緒，請稍後重新整理。</p>}<p className="text-sm text-slate-500 mt-3">Key 不會寫入對話或瀏覽器儲存空間，儲存後不提供明文讀回。</p></section>;
}
